version: 2
jobs:
    build:
      docker:
        - image: nullworks/cathook-docker-ci-arch:latest
      steps:
        - checkout
        - run: 
            name: "Compiling cathook and Textmode cathook"
            command: git submodule update --init --recursive; mkdir build; cd build; cmake -DEnableWarnings=0 -DCMAKE_BUILD_TYPE=Release -DVisuals_DrawType="Textmode" -DVACBypass=1 -DEnableWarnings=0 ..; make -j8; cd ..
